-- MySQL Script generated by MySQL Workbench
-- sáb 08 jul 2023 10:26:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbLosNotas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbLosNotas` ;

-- -----------------------------------------------------
-- Schema dbLosNotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbLosNotas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbLosNotas` ;

-- -----------------------------------------------------
-- Table `dbLosNotas`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLosNotas`.`category` ;

CREATE TABLE IF NOT EXISTS `dbLosNotas`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbLosNotas`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLosNotas`.`client` ;

CREATE TABLE IF NOT EXISTS `dbLosNotas`.`client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `index3` (`id` ASC, `username` ASC, `name` ASC, `lastname` ASC, `password` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbLosNotas`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbLosNotas`.`note` ;

CREATE TABLE IF NOT EXISTS `dbLosNotas`.`note` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `content` VARCHAR(250) NOT NULL,
  `flag` VARCHAR(10) NULL DEFAULT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notes_client_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_note_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_note_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `dbLosNotas`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notes_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `dbLosNotas`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
